name: EnderPearlCoolDown
author: squid
version: 1.0
main: net.sqdmc.epc.EPC

commands:
  epc:
    description: Reload configuration
    aliases: [enderpearlcooldown]
    usage: |
      /epc reload
    permission: gringotts.admin

permissions:
  enderpearl.cooldown:
    default: true
  enderpearl.use:
    default: true
  enderpearl.admin:
    default: op