name: EnderPearlCoolDown
authors: [squidicuz, jasticE]
version: 1.0.1
main: net.sqdmc.epc.EPC

commands:
  epc:
    description: Reload configuration
    aliases: [enderpearlcooldown]
    usage: |
      /epc reload
    permission: enderpearl.admin

permissions:
  enderpearl.cooldown:
    default: true
  enderpearl.use:
    default: true
  enderpearl.admin:
    default: op